name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dd-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/dd-backend:latest

    - name: Build and Push Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dd-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/dd-frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo apt install git -y

          if [ ! -d "dd-assignment" ]; then
            git clone https://github.com/${{ github.repository }}.git dd-assignment
          fi
          
          cd dd-assignment
          git pull origin main

          sudo docker-compose down || true

          sed -i 's|build: ./backend|image: ${{ secrets.DOCKER_USERNAME }}/dd-backend:latest|g' docker-compose.yml
          sed -i 's|build: ./frontend|image: ${{ secrets.DOCKER_USERNAME }}/dd-frontend:latest|g' docker-compose.yml

          sudo docker-compose pull
          sudo docker-compose up -d